name: Release Docker Image

on:
  push:
    tags:
      - "v*" # triggers only on version tags like v1.0.0

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tag name
        id: vars
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app # 👈 points to your app folder
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/pg-webhook:latest
            ${{ secrets.DOCKER_USERNAME }}/pg-webhook:${{ env.TAG }}
